### ISSUE TITLE
app doesnt work on some old android versions.

### ISSUE THREAD

**Issue by dinura-imesh** [scoute-dich/browser#260]
I tried to install the app in some older android versions including android 7.1 and the app didnt work. works well in oreo.

**Comment by scoute-dich** [comment]
Can anyone running an older Android version (below Pie) test the following apk?
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/2970193/app-debug.apk.zip)

**Comment by HJarausch** [comment]
How can install this debug version?
I'm on Android 6.
Thanks

**Comment by Tobiplayer3** [comment]
Also can't install on Android 8. (Playstore version works for me.)

**Comment by franco27** [comment]
I explained it to you in #261,  I can no longer open your web browser after the update 6.3.1 -with Android 7.0 Nougat
version 6.2 was initially installed (and still works correctly).

impossible to run version 6.3.1 under Android 7  
"FossBrowser has stopped working ",  "FossBrowser keeps stopping."
I propose to watch this video to better understand:
https://drive.google.com/file/d/1NeQ2-4Rsga9xK24jQ_PqEgeYPumkWXqf/view?usp=sharing

**Comment by Tobiplayer3** [comment]
After looking at the logs in an Android Emulator I discovered that it seems to be "Safe Browsing" which causes the crash on Android 7.1 or older. As the docs state that "Safe Browsing is enabled by default for devices which support it." I'd suggest simply removing the problematic line.

**Comment by scoute-dich** [comment]
Thanks. I fixed it. Safe browsing is now disabled for Android =< Nougat. For Android > Nougat it's still enabled. Thanks for reporting this issue. I only have a device running Pie.

**Comment by franco27** [comment]
Yes, I confirm it's resolved.  I can now open it with the current new version.

Now I have another problem with the start page, I change the settings, but I still have the changelog and your github page displayed.    Nothing happens when I change the settings.

**Comment by scoute-dich** [comment]
Just scroll to the bottom and click the "chek" icon.

**Comment by franco27** [comment]
Thank you very much for your answer. I no longer have the changelog. 
 
But I still have your github page when you start.  I would like to participate in the project and propose a French version of your web browser.
