### ISSUE TITLE
app version 8.1 from github doesn't start

### ISSUE THREAD

**Issue by tusch001** [scoute-dich/browser#599]
Hi.
Unfotunately I can't start app version 8.1 after installation. I cleared cache and all data.

On Android 6.01 Stock it closes immediately, Android 9 shows a white or black screen and no error.

At the moment none of my phones are rooted. I could only get logs of my Android 6 phone (with adb permission READ_LOGS only, below). This didn't work for the Android 9 phone. Nothing at all in the log there.

If you need more info I can root both phones.

Let me know if I can help more.
```
<<< log_count = 11 >>>
[07-16 22:01:08.578 1231:4593 I/ActivityManager]
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=de.baumann.browser/.activity.BrowserActivity} from uid 10107 on display 0

[07-16 22:01:08.611 1231:4499 I/ActivityManager]
Start proc 17519:de.baumann.browser/u0a136 for activity de.baumann.browser/.activity.BrowserActivity

[07-16 22:01:08.643 17519:17519 W/System]
ClassLoader referenced unknown path: /data/app/de.baumann.browser-1/lib/arm64

[07-16 22:01:09.092 17519:17519 W/System.err]
	at de.baumann.browser.view.NinjaWebView.<init>(NinjaWebView.java:98)

[07-16 22:01:09.092 17519:17519 W/System.err]
	at de.baumann.browser.activity.BrowserActivity.addAlbum(BrowserActivity.java:1153)

[07-16 22:01:09.092 17519:17519 W/System.err]
	at de.baumann.browser.activity.BrowserActivity.dispatchIntent(BrowserActivity.java:512)

[07-16 22:01:09.092 17519:17519 W/System.err]
	at de.baumann.browser.activity.BrowserActivity.onCreate(BrowserActivity.java:275)

[07-16 22:01:09.207 533:533 F/DEBUG]
pid: 17519, tid: 17519, name: baumann.browser  >>> de.baumann.browser <<<

[07-16 22:01:09.360 1231:17548 W/ActivityManager]
  Force finishing activity de.baumann.browser/.activity.BrowserActivity

[07-16 22:01:09.665 1231:17548 I/WindowManager]
Screenshot max retries 4 of Token{8c9c962 ActivityRecord{3c3102d u0 de.baumann.browser/.activity.BrowserActivity t932 f}} appWin=Window{d2722ba u0 Starting de.baumann.browser} drawState=4

[07-16 22:01:09.669 1231:3580 I/ActivityManager]
Process de.baumann.browser (pid 17519) has died
```

**Comment by scoute-dich** [comment]
You mean the apk from the release site?

**Comment by tusch001** [comment]
yes, this [https://github.com/scoute-dich/browser/releases/tag/v8.1](https://github.com/scoute-dich/browser/releases/tag/v8.1)

**Comment by scoute-dich** [comment]
I released a new one. Please try 8.1.1. If this also does not work I'll see, at the weekend, what I can do.

**Comment by tusch001** [comment]
No change. Log still the same. (the unknown path still in there).
Can you unpublish the release and just go to bed?

**Comment by islam2hamy** [comment]
Also here , android 7.1.2

**Comment by woheller69** [comment]
Pull-request should fix the problem with lower android versions. Tested with 6.0.1
