### ISSUE TITLE
no password field on webserver authentication

### ISSUE THREAD

**Issue by mcarni** [scoute-dich/browser#891]
when trying to log on KODI webserver i can see the field where to enter the username but not the password

[login window on default browser](https://i.imgur.com/lZRSjeem.png)

[missing password field on FOSS Browser](https://i.imgur.com/ArmV43em.png)

hope this helps

M

**Comment by scoute-dich** [comment]
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/8361746/app-debug.apk.zip)
You can test attached apk. Please report back, if that solves the issue.

**Comment by mcarni** [comment]
sorry, i tried but it still shows me only the username field (and below the icon for night view and desktop mode) no password

sorry and thanks
M

**Comment by caywin25** [comment]
Hello, 

Yes same issue here.
Only username field when I want to access on a 401 webpage.

Thank you

**Comment by scoute-dich** [comment]
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/8638507/app-debug.apk.zip)
Next test. Should work now.

**Comment by scoute-dich** [comment]
If this issue is still from relevance after the next update, please open a new issue. With the next update, there will come a lot of layout changes and improvements.

_Also be care of enabling all features you need in the profile settings (JavaScript, disable fingerprinting, cookies, ...)._

**Comment by mcarni** [comment]
Thanks for your hard work on this.

new layout looks great, as always your work is really appreciated.

I still cannot get both fields (username & password) in the login popup.

I tried to play with the profile settings, i might have missed something...
But i tried to disable anything that could have prevented the proper display of the login page
Still I can see 1 field (username:___ ) so I am guessing it might not be a problem due to settings...but this is only my guess

I hope this helps, if not, please don't worry

thanks

M

**Comment by scoute-dich** [comment]
You have the latest commits in your build?
